version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pyqt5
    versions:
    - 5.15.2
    - 5.15.3
  - dependency-name: pyqt5-stubs
    versions:
    - 5.15.2.0
